### PR TITLE
FreeBSD compatability

### PR DESCRIPTION
**Pull request by sweco-secfha**
Cherry-picked commits related to FreeBSD compatibility with some small tweaks.

### CODE REVIEW

**Comment by tijuca** [comment]
Thanks for collecting the changes you made for a successful build.

Some of your cherry-picks seems to be modified in some way so git isn't using the original author. And please use option `-x` while using `git cherry-pick`, by this a directly reference to the picked commit is included in the commit message.

d65176b is original aa7256a8
aec7eff is original 6a5b12a7

Please explain a bit why you have done 3b897c2 and 69778de
[CONTRIBUTE - 5.5 Patches and Commits](https://github.com/obgm/libcoap/blob/develop/CONTRIBUTE#L163)

**Comment by tijuca** [comment]
No feedback so far, please give some more information and prepare an update if you like have merged your changes.

**Comment by mblund** [comment]
@sweco-secfha, are you able to answer @tijuca questions? I would love to get this to work in a jail on my freenas box.

**Comment by obgm** [comment]
PR #280 should resolve outstanding FreeBSD-related issues. Can you confirm?

**Comment by sweco-secfha** [comment]
@mblund I'm sorry, I totally lost this and don't remember what have to be done. I hope the PR @obgm links to helps you out.

**Comment by tijuca** [comment]
This issues can be closed I'd say.
The RC3 has built on [kfreebsd-amd64](https://buildd.debian.org/status/fetch.php?pkg=libcoap2&arch=kfreebsd-amd64&ver=4.2.0%7Erc3-1&stamp=1545387134&raw=0) and [kfreebsd-i386](https://buildd.debian.org/status/fetch.php?pkg=libcoap2&arch=kfreebsd-i386&ver=4.2.0%7Erc3-1&stamp=1545393183&raw=0).

**Pull request closed without merging**
