### PR TITLE
coap_mbedtls.c: verify certificate after successful handshake

### PR DESCRIPTION
**Pull request by obgm**
Peter van der Stok has pointed out that according to the documentation,
the server certificates should be verified when peer verification is not
used. As a resolution, he has created this fix.

Signed-off-by: Peter van der Stok <consultancy@vanderstok.org>

### CODE REVIEW

**Comment by obgm** [comment]
@mrdeep1 can you have a look at this proposal? The issue was that OpenSSL and MbedTLS showed a different behavior when `require_peer_cert` was set to 1.

**Comment by mrdeep1** [comment]
Sure

**Comment by mrdeep1** [comment]
Following offline discussions with Peter it transpires that if the coap-client and coap-server use different self-signed certificates (i.e there is not  common CA signing both the certificates so mutual authentication cannot take place at the (D)TLS layer) the disparities occur.  These disparities will be worked through for the different (D)TLS libraries that support PKI so that what occurs is consistent (with potentially modified) libcoap documentation.

There are various flags that can be set or unset when setting up a PKI session and I have added some additional clarity
````
  uint8_t verify_peer_cert;        /**< 1 if peer cert is to be verified */
  uint8_t require_peer_cert;       /**< 1 if peer cert is required */
  uint8_t allow_self_signed;       /**< 1 if self signed certs are allowed */
  uint8_t allow_expired_certs;     /**< 1 if expired certs are allowed */
  uint8_t cert_chain_validation;   /**< 1 if to check cert_chain_verify_depth */
  uint8_t cert_chain_verify_depth; /**< recommended depth is 3 */
  uint8_t check_cert_revocation;   /**< 1 if revocation checks wanted */
  uint8_t allow_no_crl;            /**< 1 ignore if CRL not there */
  uint8_t allow_expired_crl;       /**< 1 if expired crl is allowed */
````
`verify_peer_cert` set causes the logic to check that both certificates are signed by a common CA, if not this is a failure, so un-setting this in Peter's case is what is required.  If a peer certificate is not received, then this CA test does not take place.

`require_peer_cert `set instructs the server to request the client to send its certificate.  If the client fails to send a certificate, then this is a failure.  Not setting this on a client, but `verify_peer_cert `is set is where the ambiguities come in and needs to be fixed.

`allow_self_signed` needs to be set if there is any certificate that is set in the CA chain that is self-signed (which also includes the CA) and `verify_peer_cert `is set.

`cert_chain_verify_depth `is the certificate chain length back to the common CA (count includes both the peer cert and its CA) including any interim CA.

**Comment by obgm** [comment]
As PR #561 has been merged, I think this can be closed off, correct?

**Comment by mrdeep1** [comment]
Yes, this can be closed

**Pull request closed without merging**
