### PR TITLE
Add documentation for flags used in resources creation.

### PR DESCRIPTION
**Pull request by KurdyMalloy**
Add documentation based on a question in the mailing list.

### CODE REVIEW

**Comment by obgm** [comment]
Thank you. Can you please replace the '-' in RFC-7641 by a white space as this is more common?
By ' 4.5', you probably mean ', Section 4.5'?
I wonder if you could include a hyperlink for more convenient access to that document.

**Comment by tijuca** [comment]
And please take care of paragraph 5.5 from [CONTRIBUTE](https://github.com/obgm/libcoap/blob/develop/CONTRIBUTE#L161) and add some prefix to the commit topic, this helps not only me to go through all commits if needed.

**Comment by KurdyMalloy** [comment]
I tried to squash everything in one commit with the correct topic which resulted in 3de2558, the merge (cc12a86) is a result of my lack of talent with git I suppose ;-) , I assume you can just cherry-pick 3de2558.

**Comment by obgm** [comment]
Fixed in 02c3e67.

**Pull request closed without merging**
