### PR TITLE
Various patches: naming and debug print

### PR DESCRIPTION
**Pull request by arabine**
This PR contains several patches not linked together. First I renamed various things to avoid conflict with other files ( _COAP_CONFIG_H_ is better than the generic _CONFIG_H_).

I added also some debug print which are useful to easily track bad defines.

### CODE REVIEW

**Comment by obgm** [comment]
Thank you for doing the cleanup work. A few general remarks:
* Submitting several unrelated fixes makes in this PR can block merging until the very last issue has been resolved.
* The contribution guidelines suggest to prefix commits with the name of the changed source file(s) as common in many other OSS projects.
* Some of the commits introduce changes that are reverted in a other commits. A "cleaned" version will be much easier to review.

**Comment by tijuca** [comment]
And please prevent merge commits from the current upstream development. Please do a rebase against the current develop branch instead and do a force push to your branch on GH.

**Comment by mrdeep1** [comment]
Hi @arabine Thanks for doing the initial development work on this one.

@obgm I have just checked, and all of the changes are in #208 which has been merged.

**Comment by obgm** [comment]
OK, so we can close this now. Thanks @arabine and @mrdeep1 for resolving this.

**Pull request closed without merging**
