### PR TITLE
Assorted build fixes

### PR DESCRIPTION
**Pull request by diego-santacruz**
I encountered a few issues while building libcoap with DTLS support and I would like to push the fixes.

The first two concern building outside the source tree (for cleaner builds). 

The third one is to avoid exposing the SSL lib via pkg-config to libcoap users when not required as it can create problems in some scenarios.

### CODE REVIEW

**Comment by obgm** [comment]
@tijuca, can you have a look at this as well? Since you have done the out-of-tree build, you might have an opinion on the removal of `-isystem`.

**Comment by tijuca** [comment]
I'm fine with those changes but haven't done any checking on this. I expect @diego-santacruz has done a proper testing before raising a pull request. If we look further in the future we need to create some more test cases that will be run by Travis or a make target at least.

**Comment by diego-santacruz** [comment]
I did test this in the context of a native Linux x64 build and also on a Yocto cross-compile and both work fine.

Diego Santa Cruz

Le 20 sept. 2017 à 19:35, tijuca <notifications@github.com<mailto:notifications@github.com>> a écrit :


I'm fine with those changes but haven't done any checking on this. I expect @diego-santacruz<https://github.com/diego-santacruz> has done a proper testing before raising a pull request. If we look further in the future we need to create some more test cases that will be run by Travis or a make target at least.

**Comment by tijuca** [comment]
Yeah, then just go ahead.

**Pull request merged**
