### PR TITLE
Byte alignment improvement

### PR DESCRIPTION
**Pull request by gli-spirent**
Small improvement and reminder for Byte alignment issue in the feature

### CODE REVIEW

**Comment by mrdeep1** [comment]
Please do not mix completely different pull requests in the same PR.   Furthermore see comments on #326 as to why https://github.com/obgm/libcoap/pull/315/commits/58dfca0edd2d0030e9e7d29af54bd6db52cc0ccb is bad and should be removed from this PR.

**Comment by gli-spirent** [comment]
Sure. Do you need me to backout the change?

**Comment by mrdeep1** [comment]
Yes please, back out https://github.com/obgm/libcoap/commit/58dfca0edd2d0030e9e7d29af54bd6db52cc0ccb .

**Comment by tijuca** [comment]
Hmm, that's not the way it should go. Please use a local rebase to clean up your PR branch and do a force push afterwards. This is simply to have a more clean history to not hassle with unrelated commits. Also be a bit more declarative in the commit message. I've no clue why your commit is needed and what possible problem it will solve. Thanks.

**Comment by gli-spirent** [comment]
Will close the pull request and do it again.

**Pull request closed without merging**
