### PR TITLE
debug: prefix debug message macros with coap_

### PR DESCRIPTION
**Pull request by gebart**
automated replacement using 

```
sed -i -e 's/\binfo(/coap_info(/g' -e 's/\bwarn(/coap_warn(/g' -e 's/\bdebug(/coap_debug(/g' {include/coap,src,examples}/*.[ch]
```

### CODE REVIEW

**Comment by gebart** [comment]
partly addresses #50

**Comment by tijuca** [comment]
Hello @gebart,

I'm o.k. with this changes. Would you please rebase your changes and expand the commit message about why this commit make sense? I'd be o.k. to use the message in the bug report #50 as this explains exactly why this changes are useful. If the travis builds are successful Olaf will probably pull you fixes a believe.

**Comment by gebart** [comment]
I will update this when I find the time. I don't understand however why the Travis build fails on what seems like building documentation. Any ideas?

**Comment by tijuca** [comment]
Thanks.
The issues with the Travis test build are not related to your original changes. As far as I remember the chroot of the Travis was changed and we found a broken pkg-config file for libcunit1-dev. Olaf was working around this problem with a hackish change https://github.com/obgm/libcoap/commit/ab198868f196de1e7ebc36692be4d86c9538c0f4 of the pkg-config file before starting the tests.

**Comment by tijuca** [comment]
Hmm, unfortunately this PR hasn't made it until now. Could you please rebase your modifications once again? I had no luck with a local try to rebase your branch, so maybe you will just need to re-use your sed command?

**Comment by obgm** [comment]
Closing as this has been resolved in PR #269.

**Pull request closed without merging**
