### PR TITLE
refactor: move headers to namespace

### PR DESCRIPTION
**Pull request by gocarlos**
# what
put headers in namespace e.g. `#include "option.h"` to `#include "coap2/option.h"`

# why
* make it clear from where each header file comes from -> readability
* prevent collisions with legacy code which often used `net.h`, `str.h` -> important in bigger projects as edge gateways with multiple protocol stacks, some not maintained anymore
* consequent, as some files were already using the `#include "coap2/option.h"` version, the majority though was using the  `#include "option.h"`

### CODE REVIEW

**Comment by mrdeep1** [comment]
As mentioned in #433 (which needs to be closed) to allow this code to build on travis

This is failing to compile in the Travis build as Makefile.am is not setting up the correct include directories as per
````
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -I./include/coap2 -I./include/coap2 -pedantic -Wall -Wcast-qual -Wextra -Wformat-security -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wunused -Wwrite-strings -Wlogical-op -Wunused-result -std=c99 -g -O2 -fdiagnostics-color -D_GNU_SOURCE -MT src/libcoap_2_la-address.lo -MD -MP -MF src/.deps/libcoap_2_la-address.Tpo -c src/address.c  -fPIC -DPIC -o src/.libs/libcoap_2_la-address.o
src/address.c:9:10: fatal error: coap2/coap_internal.h: No such file or directory
    9 | #include "coap2/coap_internal.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
````
The line in question that needs updating in Makefile.am is
````
AM_CFLAGS = -I$(top_builddir)/include/coap$(LIBCOAP_API_VERSION) -I$(top_srcdir)/include/coap$(LIBCOAP_API_VERSION) $(WARNING_CFLAGS) $(DTLS_CFLAGS) -std=c99
````
to
````
AM_CFLAGS = -I$(top_builddir)/include -I$(top_srcdir)/include $(WARNING_CFLAGS) $(DTLS_CFLAGS) -std=c99
````

**Comment by mrdeep1** [comment]
It would also help if there was a description of why both in the PR request as well as in the commit information.

**Comment by mrdeep1** [comment]
The compilation has moved on to a new issue.  Fixing that, then there are issues with the lwip and contiki example builds which Travis does as well.

The primary issue is with coap_config.h which holds the current build configuration and is not installed or available for application use.  lwip and contiki have their own pre-built coap_config.h which must be used, not the one currently built into coap2/coap_config.h

**Comment by gocarlos** [comment]
> lwip and contiki have their own pre-built coap_config.h which must be used, not the one currently built into coap2/coap_config.h

humm, this makes this task complexer :D
the goal of having a `config.h` file is exactly to deal with multiplatform/architecture/options stuff right? 
can't those `config.h` files be together e.g. using preprocessor to differentiate between targets

Right now there is also a file for windows, is beiing removed in another MR from my side

**Comment by mrdeep1** [comment]
1) include/coap2/coap_config.h.in needs to be removed from the source tree
2) tests are not building (tests/Makefile/am needs fixing) with autogen
3) coap_config.h is getting installed in error to /usr/local/include - it is only a part of the library build environment.
3) Still need to get lwip and contiki builds working and what is decided may affect the esp-idf project that uses libcoap and has its own coap_config.h.

There is a part of me that says coap_config.h should be installed in the build environment in ./include, not ./include/coap2.  Then it makes coap_config.h easier to find in the ./ or ./include directories.

Separately, with a dual stack gnutls compilation support (standard centos release and later gnutls code), using cmake builds libcoap.a with the later version of gnutls code, but links it to run against the earlier version (and hence blows up when running the test suite).  I need to check into this further as it may be something at my end - I am not adding any special cmake command line options to find the later code version.

**Comment by mrdeep1** [comment]
Moving coap_config.h to the top level directory works with all the build versions with this patch.  I have not checkout esp-idf though, but do not expect any issues with this being searched for as
````
#include "coap_config.h"
````

[refactor.txt](https://github.com/obgm/libcoap/files/4540461/refactor.txt)

There is an additional change (previously recommended) to CMakeLists.txt that better formats the output for `cmake -LH .`

**Comment by gocarlos** [comment]
> Moving coap_config.h to the top level directory works with all the build versions with this patch.

not on my side, or at least due to the other changes:

```
In file included from /usr/include/x86_64-linux-gnu/sys/socket.h:33,
                 from /usr/include/netinet/in.h:23,
                 from /home/gocarlos/git/libcoap/include/coap2/libcoap.h:27,
                 from /home/gocarlos/git/libcoap/build/include/coap2/coap.h:33,
                 from /home/gocarlos/git/libcoap/include/coap2/coap_internal.h:36,
                 from /home/gocarlos/git/libcoap/src/coap_io.c:9:
/home/gocarlos/git/libcoap/src/coap_io.c: In function ‘coap_network_send’:
/home/gocarlos/git/libcoap/src/coap_io.c:553:32: error: invalid application of ‘sizeof’ to incomplete type ‘struct in6_pktinfo’
  553 |     char buf[CMSG_SPACE(sizeof(struct in6_pktinfo))];
      |                                ^~~~~~
/home/gocarlos/git/libcoap/src/coap_io.c:612:49: error: invalid application of ‘sizeof’ to incomplete type ‘struct in6_pktinfo’
  612 |         mhdr.msg_controllen = CMSG_SPACE(sizeof(struct in6_pktinfo));
      |                                                 ^~~~~~
/home/gocarlos/git/libcoap/src/coap_io.c:617:42: error: invalid application of ‘sizeof’ to incomplete type ‘struct in6_pktinfo’
  617 |         cmsg->cmsg_len = CMSG_LEN(sizeof(struct in6_pktinfo));
      |                                          ^~~~~~
/home/gocarlos/git/libcoap/src/coap_io.c:621:16: error: dereferencing pointer to incomplete type ‘struct in6_pktinfo’
  621 |         pktinfo->ipi6_ifindex = session->ifindex;
      |                ^~
In file included from /usr/include/x86_64-linux-gnu/sys/socket.h:33,
                 from /usr/include/netinet/in.h:23,
                 from /home/gocarlos/git/libcoap/include/coap2/libcoap.h:27,
                 from /home/gocarlos/git/libcoap/build/include/coap2/coap.h:33,
                 from /home/gocarlos/git/libcoap/include/coap2/coap_internal.h:36,
                 from /home/gocarlos/git/libcoap/src/coap_io.c:9:
/home/gocarlos/git/libcoap/src/coap_io.c: In function ‘coap_network_read’:
/home/gocarlos/git/libcoap/src/coap_io.c:756:32: error: invalid application of ‘sizeof’ to incomplete type ‘struct in6_pktinfo’
  756 |     char buf[CMSG_SPACE(sizeof(struct in6_pktinfo))];
      |                                ^~~~~~
/home/gocarlos/git/libcoap/src/coap_io.c:832:38: error: dereferencing pointer to incomplete type ‘struct in6_pktinfo’
  832 |           packet->ifindex = (int)(u.p->ipi6_ifindex);
      |                                      ^~
make[2]: *** [CMakeFiles/coap.dir/build.make:219: CMakeFiles/coap.dir/src/coap_io.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:221: CMakeFiles/coap.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by mrdeep1** [comment]
This looks to me like you have a stale coap_config.h file that needs to be removed.

**Comment by gocarlos** [comment]
> Moving coap_config.h to the top level directory works with all the build versions with this patch. I have not checkout esp-idf though, but do not expect any issues with this being searched for as
> 
> ```
> #include "coap_config.h"
> ```
> 
> [refactor.txt](https://github.com/obgm/libcoap/files/4540461/refactor.txt)
> 
> There is an additional change (previously recommended) to CMakeLists.txt that better formats the output for `cmake -LH .`

why not installing `utlist.h`? I know its not part of this lib, though if we do not install it -> cannot use headers as its used in public headers

> This looks to me like you have a stale coap_config.h file that needs to be removed.

Thats why I hate in source builds, was testing autoconf for this MR...

**Comment by mrdeep1** [comment]
That code push does not give me any build errors, so if there are still some, then more debugging is needed - what is your build environment?

**Comment by gocarlos** [comment]
> That code push does not give me any build errors, so if there are still some, then more debugging is needed - what is your build environment?

no, sorry, misunderstanding, everything ok also on my side

**Comment by mrdeep1** [comment]
@gocarlos Can you please rebase this PR using the latest develop.  @obgm has moved build coap_config.h from include/coap2/coap_config.h to ./coap_config.h.  This PR moves it to include/coap_config.h.  ./coap_config.h should be fine.

**Comment by obgm** [comment]
Closed as superseded by PR #606.

**Pull request closed without merging**
